"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import logo from "./Images/download.png";
import { Input } from "../components/ui/input";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faBars,
  faSearch,
  faShoppingCart,
} from "@fortawesome/free-solid-svg-icons";
import MenuBar from "@/components/MenuBar";
import { useState } from "react";
import Cart from "../app/cart/page";
import { Providers } from "./providers";
import { Button, useDisclosure } from "@nextui-org/react";
import { useForm } from "react-hook-form";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "EcommercerWebsite",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isListVisible, setListVisibility] = useState(false);
  const [isCartVisible, setIsCartVisible] = useState(false);

  const { onsubmit, error } = useForm();

  console.log("isCartVisible: ", isCartVisible);

  const handleClick = () => {
    console.log("working");
    setIsCartVisible(true);
  };

  // const { isOpen, onOpen, onOpenChange, onClose } = useDisclosure({
  //   isOpen: isCartVisible,
  //   onClose: () => setCartVisibility(false),
  // });
  // console.log("isOpen: ", isOpen);

  const toggleListVisibility = () => {
    setListVisibility(!isListVisible);
  };

  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <div className="dark">
            <div className="flex flex-row">
              <div className="md:hidden w-full">
                <div className="flex justify-between">
                  <div
                    className="relative top-[5px] cursor-pointer"
                    onClick={toggleListVisibility}
                  >
                    <FontAwesomeIcon
                      icon={faBars}
                      className="h-6 text-white m-6"
                    />
                    {isListVisible && (
                      <div
                        onClick={toggleListVisibility}
                        className="fixed top-0 left-0 text-white flex flex-col bg-gray-800 p-4 rounded-md shadow-lg w-screen z-10"
                      >
                        <div
                          onClick={(e) => e.stopPropagation()}
                          className="relative w-full h-full"
                        >
                          <button
                            onClick={toggleListVisibility}
                            className="mb-4 bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded max-w-min"
                          >
                            Back
                          </button>
                          <div className="flex items-center justify-center align-middle ">
                            <Input
                              placeholder="search for products..."
                              className="font-medium m-3 rounded- pl-5 text-white"
                              // style={{ color: "#919191" }}
                            />
                            <FontAwesomeIcon
                              icon={faSearch}
                              className="ml-2 w-4 relative right-[3rem] font-black text-white"
                            />
                          </div>

                          <Link href={"/"} onClick={toggleListVisibility}>
                            <span className="block py-2 px-4 hover:bg-gray-700 rounded-md">
                              Home
                            </span>
                          </Link>
                          <Link href={"/all"} onClick={toggleListVisibility}>
                            <span className="block py-2 px-4 hover:bg-gray-700 rounded-md">
                              ALL
                            </span>
                          </Link>
                          <Link
                            href={"/all/stickers"}
                            onClick={toggleListVisibility}
                          >
                            <span className="block py-2 px-4 hover:bg-gray-700 rounded-md">
                              Stickers
                            </span>
                          </Link>
                          <Link
                            href={"/all/shirts"}
                            onClick={toggleListVisibility}
                          >
                            <span className="block py-2 px-4 hover:bg-gray-700 rounded-md">
                              Shirts
                            </span>
                          </Link>
                        </div>
                      </div>
                    )}
                  </div>
                  <div className="flex flex-row m-6 gap-3 items-center">
                    <Link href={"/"}>
                      <Image
                        src={logo}
                        alt="Logo"
                        width={40}
                        height={10}
                        className="rounded-[15%] borde-0 w-10 h-8"
                      />
                    </Link>
                    <Link href={"/"}>
                      <span className="font-medium text-[15px] font-sans text-white">
                        ACME STORE
                      </span>
                    </Link>
                  </div>
                  <div className="flex items-center justify-end md:ml-auto pr-4">
                    <Button
                      className="border-[2px] rounded-[10px] border-[#404040] h-10 w-10 flex items-center justify-center"
                      onClick={handleClick}
                      // onPress={onOpen}
                    >
                      <FontAwesomeIcon
                        icon={faShoppingCart}
                        className="h-4 text-white flex justify-end"
                      />
                    </Button>
                    {/* {isOpen && <Cart state={isOpen} />} */}
                    {
                      <Cart
                        isOpen={isCartVisible}
                        onClose={() => setIsCartVisible(false)}
                      />
                    }
                  </div>
                </div>
              </div>
              <div className="flex flex-row m-6 gap-3 items-center max-md:hidden">
                <Link href={"/"}>
                  <Image
                    src={logo}
                    alt="Logo"
                    width={40}
                    height={10}
                    className="rounded-[15%] borde-0 w-10 h-8"
                  />
                </Link>
                <Link href={"/"}>
                  <span className="font-medium text-[15px] font-sans text-white ">
                    ACME STORE
                  </span>
                </Link>
              </div>
              <div className="flex-row text-[#a2a2a2] text-[15px] items-center gap-8 md:w-1/4 hidden md:flex">
                <Link href={"/all"}>
                  <span>ALL</span>
                </Link>
                <Link href={"/all/stickers"}>
                  <span>Stickers</span>
                </Link>
                <Link href={"/all/shirts"}>
                  <span>Shirts</span>
                </Link>
              </div>
              <div className="flex items-center justify-center align-middle md:max-w-96 lg:min-w-96 max-lg:max-w-96">
                <Input
                  placeholder="Search for products..."
                  className="font-medium m-3 rounded- pl-5  md:max-w-96 lg:min-w-96 max-lg:max-w-96 hidden md:flex"
                  style={{ color: "#919191" }}
                  type="text"
                />
                <FontAwesomeIcon
                  icon={faSearch}
                  className="ml-2 w-4 relative right-[3rem] font-black text-white md:w-1/4 hidden md:flex"
                />
              </div>

              <div className="flex items-center justify-end md:ml-auto pr-4 max-md:hidden">
                <Button
                  className="border-[2px] rounded-[10px] border-[#404040] h-10 w-10 flex items-center justify-center"
                  onClick={handleClick}
                  // onPress={onOpen}
                >
                  <FontAwesomeIcon
                    icon={faShoppingCart}
                    className="h-4 text-white flex justify-end"
                  />
                </Button>
                {/* {<Cart isOpen={isOpen} onClose={() => se} />} */}
                {
                  <Cart
                    isOpen={isCartVisible}
                    onClose={() => setIsCartVisible(false)}
                  />
                }
              </div>
            </div>
            <Providers>{children}</Providers>
            <footer className="text-sm text-neutral-500 dark:text-neutral-400 p-11">
              <div className="flex flex-row gap-10 max-md:flex-col">
                <div className="grid grid-flow-col gap-4 justify-center">
                  <Link href={"/"}>
                    <div>
                      <Image
                        src={logo}
                        alt="Logo"
                        className="border-[2px] rounded-[10px] w-12 h-12 max-w-28"
                      />
                    </div>
                  </Link>
                  <div className="flex justify-center text-center">
                    <Link href={"/"}>
                      <span className="font-medium text-[15px] max-text-xs font-sans text-white">
                        ACME STORE
                      </span>
                    </Link>
                  </div>
                </div>
                <div className="flex flex-col gap-4">
                  <div className="hover:underline font-bold">
                    <Link href={"/"}>
                      <h1>Home</h1>
                    </Link>
                  </div>
                  <div className="hover:underline font-bold">
                    <Link href={"/about"}>About</Link>
                  </div>
                  <div className="hover:underline font-bold">
                    <Link href={"/termsandconditions"}>Terms & Conditions</Link>
                  </div>
                  <div className="hover:underline font-bold">
                    <Link href={"/shippingandreturnpolicy"}>
                      Shipping & Return Policy
                    </Link>
                  </div>
                  <div className="hover:underline font-bold">
                    <Link href={"/privacypolicy"}>Privacy Policy</Link>
                  </div>
                  <div className="hover:underline font-bold">
                    <Link href={"/faq"}>FAQ</Link>
                  </div>
                </div>
                <div className="md:ml-auto">
                  <div className="border-[1px] border-white bg-black p-2 font-bold text-white rounded-[9px] flex justify-center">
                    <Link href={"/deploy"}>Deploy</Link>
                  </div>
                </div>
              </div>
            </footer>
            <hr className="border-[1.5px]"></hr>
            <div className="flex flex-row gap-1 items-center max-md:flex-col">
              <div>
                <p className="text-[#8a8a8a] text-[15px] font-medium p-6 ">
                  © 2024 Gampa Abhishek. All rights reserved
                </p>
              </div>
              <div>
                <span className="text-[#8a8a8a]">|</span>
              </div>
              <div>
                <p className="text-[#8a8a8a] text-[15px] font-medium  p-6">
                  Designed by Gampa Abhishek
                </p>
              </div>
              <div className="md:ml-auto">
                <p className="text-[#8a8a8a]  pr-3 font-medium">
                  Crafted by : Product of Gampa Abhishek
                </p>
              </div>
            </div>
          </div>
        </body>
      </html>
    </>
  );
}
